version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "20:00"
  open-pull-requests-limit: 10
  reviewers:
  - yamadayuki
  ignore:
  - dependency-name: "@babel/helper-plugin-utils"
    versions:
    - 7.12.13
    - 7.13.0
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
  registries:
  - npm-registry-registry-npmjs-org
